#!/usr/bin/python3
from equi_model.user import User
from equi_model import storage

dict_x = storage.all()
print('---------------Reloading-------------')
for d in dict_x.keys():
    obj = dict_x[d]
    print(obj)
print('--------------Creating New Object ---------')
alx = User()
alx.first_name = "John"
alx.last_name ="Smith"
alx.address = "No 6 Itiam Street"
alx.email = "harryjohnwhye@gmail.com"
alx.phone_no = "08033999309"
alx.gender = "Male"
alx.password = "root"
alx.city = "Eket"
alx.state = "Akwa-Ibom"
alx.save()
print('-------------Showing Created models----------')
print(alx)
print('----------Saving Action-------------')

